name: auto_tag
on:
  push:
    branches:
      - main
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: status of repo
        run: git status
